name: badguy-proxy

on:
  workflow_dispatch:


jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: badguy-step
        uses: ./.github/workflows/badguy.yml

  on-failure:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: info
        run: echo Will not run bc main failed
