name: badguy

on:
  workflow_dispatch:
  workflow_call:

env:
  CAKE: bake

jobs:
  another-job:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, badguy bad_job!
      - name: fail
        run: exit 1