name: trigger for e2e tests

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ deploy to production ]
    types: [ completed ]

jobs:

  on-success:
    uses: ./.github/workflows/another.yml

