name: badguy-proxy

on:
  workflow_dispatch:

jobs:

  on-success:
    uses: ./.github/workflows/failthingy.yml


  on-failure:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: info
        run: echo Will not run bc main failed
