name: failthingy

on:
  workflow_dispatch:
  workflow_call:

env:
  CAKE: bake

jobs:
  failinghard:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script on failure
        run: echo Hello, failing!
      - name: fail
        run: exit 1

