name: kliet

on:
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        description: Publish binaries to S3?

defaults:
  run:
    working-directory: mydir

env:
  cake-name: cake

jobs:
  cake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello cake
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          path: mydir/foo.txt
          name: ${{ env.cake-name }}
          if-no-files-found: error

  bake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello bake
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          path: mydir/foo.txt
          name: bake
          if-no-files-found: error

  cookie:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello cookie
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          path: mydir/foo.txt
          name: cookie
          if-no-files-found: error

  publishing:
    name: Publish binaries to S3
    runs-on: ubuntu-latest
    needs: [cake, bake, cookie]
    if:  ${{ inputs.publish }}
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello publishing
      - name: download
        uses: actions/download-artifact@v3
        with:
          path: target/bakeacake
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: target/bakeacake
      - name: Display structure of default working  dir
        run: ls -R
      - name: Display structure of home dir
        run: ls -R
        working-directory: .
      - name: zip
        working-directory: target/bakeacake
        run: |
          mkdir zips
          zip -j zips/${{ env.cake-name }} ${{ env.cake-name }}/*
          zip -j zips/bake bake/*
          zip -j zips/cookie cookie/*
          ls -R
      - name: Display structure of home dir
        run: ls -R
        working-directory: .

