name: slowthingy

on:
  workflow_dispatch:
  workflow_call:

concurrency: ci-slowthingy

jobs:
  slooow:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script on failure
        run: echo Hello, failing!
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash


