name: version bump

on:
  workflow_dispatch:

env:
  extension-name: my-awesome-package

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: New version in package.json
        run: | 
          echo "NEW_VERSION=$(npm version patch)" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$(npm run getName -s)" >> $GITHUB_ENV
          more package.json
          git status
      - name: build extension
        run: |
          npm install --global @vscode/vsce
          vsce package
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.PACKAGE_NAME }}*.vsix
          name: ${{ env.PACKAGE_NAME }}_${{ env.NEW_VERSION }}
      - name: Push package.json
        run: git push