name: version bump

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          git config user.email "cake"
          git config user.name "bake"
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: more package.json
      - run: npm version patch
      - run: more package.json