name: version bump

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        options:
          - major
          - minor
          - patch
        description: Choose what to bump.

env:
  extension-name: my-awesome-package

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: New version in package.json
        run: | 
          npm version ${{ inputs.bump }}
          more package.json
          git status
      - name: build extension
        run: |
          npm install --global @vscode/vsce
          vsce package
      - name: Upload
        uses: actions/upload-artifact@v3
        with:windows
          path: ./*.vsix
          name: vsix-package
      - name: Publish to s3
        run: echo "hello publish"
      - name: Push package.json
        run: git push