name: with cache

on:
  workflow_dispatch:


jobs:
  cake:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello cake
      - uses: actions/checkout@v3
      - name: create a file
        run: |
          mkdir ulrika
          touch ulrika/cake.txt
          echo "caaaaaaaaake" > ulrika/cake.txt
      - name: cache
        uses: actions/cache@v3
        with:
          path: ulrika/cake.txt
          key: mycake

  bake:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello bake
      - name: create a file
        run: |
          mkdir ulrika
          touch ulrika/bake.txt
          echo "bake bake bake" > ulrika/bake.txt
      - name: cache
        uses: actions/cache@v3
        with:
          path: ulrika/bake.txt
          key: mybake

  cookie:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello cookie
      - name: create a file
        run: |
          mkdir ulrika
          touch ulrika/cookie.txt
          echo "cookie cookie cookie" > ulrika/cookie.txt
      - name: cache
        uses: actions/cache@v3
        with:
          path: ulrika/cookie.txt
          key: mycookie

  publishing:
    name: Publish binaries to S3
    runs-on: ubuntu-latest
    needs: [cake, bake, cookie]
    steps:
      - run: echo Hello publishing
      - uses: actions/checkout@v3
      - name: cache
        uses: actions/cache@v3
        with:
          path: ulrika/cake.txt
          key: mycake
      - name: cache
        uses: actions/cache@v3
        with:
          path: ulrika/bake.txt
          key: mybake
      - name: Display structure of root dir
        run: ls -R
      - name: check content of cake.txt
        run: more ulrika/cake.txt
