name: with inputs

on:
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        description: Publish binaries to S3?


jobs:
  cake:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello cake
      - uses: actions/checkout@v3
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          path: README.md
          name: cake.md
          if-no-files-found: error

  bake:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello bake

  cookie:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello cookie

  publishing:
    name: Publish binaries to S3
    runs-on: ubuntu-latest
    needs: [cake, bake, cookie]
    if:  ${{ inputs.publish }}
    steps:
      - run: echo Hello publishing
      - name: download
        uses: actions/download-artifact@v3
        with:
          name: cake.md

